import type { Product, Order, Supplier, AnalyticsSummary, EmailCampaign, ChatMessage } from "./types";

export const mockProducts: Product[] = [
  {
    id: "prod-001",
    name: "Wireless Bluetooth Earbuds Pro",
    description: "Premium noise-cancelling earbuds with 30hr battery life and IPX5 water resistance.",
    category: "Tech Accessories",
    cost: 12.50,
    price: 39.99,
    margin: 68.7,
    supplierId: "sup-001",
    imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=400",
    inStock: true,
    createdAt: "2025-06-15T10:30:00Z",
  },
  {
    id: "prod-002",
    name: "Smart Posture Corrector",
    description: "Wearable device that vibrates when you slouch. App-connected with progress tracking.",
    category: "Health & Wellness",
    cost: 8.20,
    price: 29.99,
    margin: 72.7,
    supplierId: "sup-002",
    imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
    inStock: true,
    createdAt: "2025-06-20T14:00:00Z",
  },
  {
    id: "prod-003",
    name: "Minimalist Desk Lamp with Wireless Charger",
    description: "LED desk lamp with 5 brightness levels, touch control, and built-in Qi wireless charger.",
    category: "Home Goods",
    cost: 15.75,
    price: 49.99,
    margin: 68.5,
    supplierId: "sup-003",
    imageUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=400",
    inStock: true,
    createdAt: "2025-07-01T09:00:00Z",
  },
  {
    id: "prod-004",
    name: "Portable Blender Bottle",
    description: "USB-C rechargeable blender for smoothies and shakes on the go. 400ml capacity.",
    category: "Health & Wellness",
    cost: 10.30,
    price: 34.99,
    margin: 70.6,
    supplierId: "sup-004",
    imageUrl: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400",
    inStock: true,
    createdAt: "2025-07-05T16:30:00Z",
  },
  {
    id: "prod-005",
    name: "Magnetic Phone Mount for Car",
    description: "Ultra-strong magnetic car mount with 360° rotation, compatible with all smartphones.",
    category: "Tech Accessories",
    cost: 4.90,
    price: 19.99,
    margin: 75.5,
    supplierId: "sup-001",
    imageUrl: "https://images.unsplash.com/photo-1611077544637-6a462b87e4a1?w=400",
    inStock: false,
    createdAt: "2025-07-10T11:00:00Z",
  },
];

export const mockOrders: Order[] = [
  {
    id: "ord-001",
    productId: "prod-001",
    productName: "Wireless Bluetooth Earbuds Pro",
    customerName: "Sarah Johnson",
    customerEmail: "sarah.j@example.com",
    quantity: 1,
    total: 39.99,
    status: "delivered",
    paymentStatus: "paid",
    createdAt: "2025-07-20T08:15:00Z",
    shippedAt: "2025-07-21T10:00:00Z",
  },
  {
    id: "ord-002",
    productId: "prod-003",
    productName: "Minimalist Desk Lamp with Wireless Charger",
    customerName: "Mike Chen",
    customerEmail: "mike.c@example.com",
    quantity: 2,
    total: 99.98,
    status: "shipped",
    paymentStatus: "paid",
    createdAt: "2025-07-22T14:30:00Z",
    shippedAt: "2025-07-23T09:00:00Z",
  },
  {
    id: "ord-003",
    productId: "prod-002",
    productName: "Smart Posture Corrector",
    customerName: "Emily Davis",
    customerEmail: "emily.d@example.com",
    quantity: 1,
    total: 29.99,
    status: "processing",
    paymentStatus: "paid",
    createdAt: "2025-07-24T11:45:00Z",
    shippedAt: null,
  },
  {
    id: "ord-004",
    productId: "prod-005",
    productName: "Magnetic Phone Mount for Car",
    customerName: "Alex Rivera",
    customerEmail: "alex.r@example.com",
    quantity: 1,
    total: 19.99,
    status: "pending",
    paymentStatus: "failed",
    createdAt: "2025-07-25T09:20:00Z",
    shippedAt: null,
  },
];

export const mockSuppliers: Supplier[] = [
  {
    id: "sup-001",
    name: "AliExpress",
    platform: "AliExpress",
    productCount: 12,
    averageShippingDays: 14,
    rating: 4.2,
    status: "active",
    contactEmail: "supplier1@aliexpress.com",
  },
  {
    id: "sup-002",
    name: "CJDropshipping",
    platform: "CJDropshipping",
    productCount: 8,
    averageShippingDays: 10,
    rating: 4.5,
    status: "active",
    contactEmail: "supplier2@cjdropshipping.com",
  },
  {
    id: "sup-003",
    name: "Spocket",
    platform: "Spocket",
    productCount: 5,
    averageShippingDays: 7,
    rating: 4.7,
    status: "active",
    contactEmail: "supplier3@spocket.com",
  },
  {
    id: "sup-004",
    name: "Zendrop",
    platform: "Zendrop",
    productCount: 3,
    averageShippingDays: 12,
    rating: 4.0,
    status: "active",
    contactEmail: "supplier4@zendrop.com",
  },
  {
    id: "sup-005",
    name: "Printful",
    platform: "Printful",
    productCount: 2,
    averageShippingDays: 8,
    rating: 4.6,
    status: "inactive",
    contactEmail: "supplier5@printful.com",
  },
];

export const mockAnalytics: AnalyticsSummary = {
  totalRevenue: 12450.75,
  totalOrders: 287,
  totalVisitors: 8420,
  conversionRate: 3.41,
  averageOrderValue: 43.38,
  returnRate: 2.1,
  topTrafficChannel: "Instagram Ads",
  dailyRevenue: [
    { date: "2025-07-19", revenue: 380 },
    { date: "2025-07-20", revenue: 520 },
    { date: "2025-07-21", revenue: 445 },
    { date: "2025-07-22", revenue: 610 },
    { date: "2025-07-23", revenue: 390 },
    { date: "2025-07-24", revenue: 680 },
    { date: "2025-07-25", revenue: 510 },
  ],
};

export const mockEmailCampaigns: EmailCampaign[] = [
  {
    id: "camp-001",
    name: "Welcome Series",
    type: "welcome",
    subject: "Welcome to DropAI! 🎉 Here's 10% off your first order",
    status: "active",
    sentCount: 342,
    openRate: 68.4,
    clickRate: 24.1,
    lastSent: "2025-07-25T08:00:00Z",
  },
  {
    id: "camp-002",
    name: "Order Confirmation",
    type: "order_confirmation",
    subject: "Your DropAI order #{{orderId}} is confirmed!",
    status: "active",
    sentCount: 287,
    openRate: 92.3,
    clickRate: 45.7,
    lastSent: "2025-07-25T09:30:00Z",
  },
  {
    id: "camp-003",
    name: "Shipping Updates",
    type: "shipping_notification",
    subject: "Good news! Your order is on the way 🚚",
    status: "active",
    sentCount: 215,
    openRate: 88.9,
    clickRate: 52.3,
    lastSent: "2025-07-25T11:00:00Z",
  },
  {
    id: "camp-004",
    name: "Abandoned Cart Recovery",
    type: "abandoned_cart",
    subject: "You left something behind... Complete your order now",
    status: "active",
    sentCount: 156,
    openRate: 45.2,
    clickRate: 18.9,
    lastSent: "2025-07-25T07:00:00Z",
  },
  {
    id: "camp-005",
    name: "Supplier Outreach",
    type: "supplier_outreach",
    subject: "New product sourcing opportunity - {{productCategory}}",
    status: "draft",
    sentCount: 0,
    openRate: 0,
    clickRate: 0,
    lastSent: null,
  },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: "msg-001",
    role: "assistant",
    content: "Hello! I'm your DropAI assistant. I can help you find trending products, write product descriptions, analyze your store performance, and more. What can I help with today?",
    timestamp: "2025-07-25T12:00:00Z",
  },
];
